name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t ultra_sound8k .

      - name: Run Docker container
        run: docker run -dp 8501:8501 --name SoundDetect ultra_sound8k
